name_map = {
    "Air Force": "Air Force",
    "Akron": "Akron",
    "Alabama": "Alabama",
    "Appalachian State": "App State",
    "Arizona": "Arizona",
    "Arizona State": "Arizona St",
    "Arkansas": "Arkansas",
    "Arkansas State": "Arkansas St",
    "Army": "Army",
    "Auburn": "Auburn",
    "Ball State": "Ball St",
    "Baylor": "Baylor",
    "Boise State": "Boise St",
    "Boston College": "Boston College",
    "Bowling Green": "Bowling Green",
    "Buffalo": "Buffalo",
    "BYU": "BYU",
    "Central Michigan": "C Michigan",
    "California": "California",
    "Charlotte": "Charlotte",
    "Cincinnati": "Cincinnati",
    "Clemson": "Clemson",
    "Coastal Carolina": "Coastal Car",
    "Colorado": "Colorado",
    "Colorado State": "Colorado St",
    "Delaware": "Delaware",
    "Duke": "Duke",
    "East Carolina": "E Carolina",
    "Eastern Michigan": "E Michigan",
    "Florida": "Florida",
    "Florida Atlantic": "Florida Atlantic",
    "Florida International": "Florida Intl",
    "Florida State": "Florida St",
    "Fresno State": "Fresno St",
    "Georgia": "Georgia",
    "Georgia Southern": "Georgia So",
    "Georgia State": "Georgia St",
    "Georgia Tech": "Georgia Tech",
    "Hawaii": "Hawai'i",
    "Houston": "Houston",
    "Illinois": "Illinois",
    "Indiana": "Indiana",
    "Iowa": "Iowa",
    "Iowa State": "Iowa St",
    "James Madison": "J Madison",
    "Jacksonville State": "Jacksonville St",
    "Kansas": "Kansas",
    "Kansas State": "Kansas St",
    "Kennesaw State": "Kennesaw St",
    "Kent State": "Kent St",
    "Kentucky": "Kentucky",
    "Liberty": "Liberty",
    "Louisiana": "Louisiana",
    "Louisiana Tech": "Louisiana Tech",
    "Louisville": "Louisville",
    "LSU": "LSU",
    "Marshall": "Marshall",
    "Maryland": "Maryland",
    "Memphis": "Memphis",
    "Miami": "Miami",
    "Miami (OH)": "Miami OH",
    "Michigan": "Michigan",
    "Michigan State": "Michigan St",
    "Middle Tennessee": "Middle Tenn",
    "Minnesota": "Minnesota",
    "Ole Miss": "Mississippi",
    "Mississippi State": "Mississippi St",
    "Missouri": "Missouri",
    "Missouri State": "Missouri St",
    "Northern Illinois": "N Illinois",
    "North Texas": "N Texas",
    "Navy": "Navy",
    "NC State": "NC State",
    "Nebraska": "Nebraska",
    "Nevada": "Nevada",
    "New Mexico": "New Mexico",
    "New Mexico State": "New Mexico St",
    "North Carolina": "North Carolina",
    "Northwestern": "Northwestern",
    "Notre Dame": "Notre Dame",
    "Ohio": "Ohio",
    "Ohio State": "Ohio St",
    "Oklahoma": "Oklahoma",
    "Oklahoma State": "Oklahoma St",
    "Old Dominion": "Old Dominion",
    "Oregon": "Oregon",
    "Oregon State": "Oregon St",
    "Penn State": "Penn St",
    "Pittsburgh": "Pittsburgh",
    "Purdue": "Purdue",
    "Rice": "Rice",
    "Rutgers": "Rutgers",
    "South Alabama": "S Alabama",
    "South Florida": "S Florida",
    "Sam Houston": "Sam Houston",
    "San Diego State": "San Diego St",
    "San Jose State": "San Jose St",
    "SMU": "SMU",
    "South Carolina": "South Carolina",
    "Southern Mississippi": "Southern Miss",
    "Stanford": "Stanford",
    "Syracuse": "Syracuse",
    "TCU": "TCU",
    "Temple": "Temple",
    "Tennessee": "Tennessee",
    "Texas": "Texas",
    "Texas A&M": "Texas A&M",
    "Texas State": "Texas St",
    "Texas Tech": "Texas Tech",
    "Toledo": "Toledo",
    "Troy": "Troy",
    "Tulane": "Tulane",
    "Tulsa": "Tulsa",
    "UAB": "UAB",
    "UCF": "UCF",
    "UCLA": "UCLA",
    "Connecticut": "UConn",
    "UL Monroe": "UL Monroe",
    "Massachusetts": "UMass",
    "UNLV": "UNLV",
    "USC": "USC",
    "Utah": "Utah",
    "Utah State": "Utah St",
    "UTEP": "UTEP",
    "UTSA": "UTSA",
    "Vanderbilt": "Vanderbilt",
    "Virginia": "Virginia",
    "Virginia Tech": "Virginia Tech",
    "Western Kentucky": "W Kentucky",
    "Western Michigan": "W Michigan",
    "Wake Forest": "Wake Forest",
    "Washington": "Washington",
    "Washington State": "Washington St",
    "West Virginia": "West Virginia",
    "Wisconsin": "Wisconsin",
    "Wyoming": "Wyoming"
}

def normalize_name(name):
    return name_map.get(name, name)