name_map = {
    "Appalachian State": "App State",
    "Arizona State": "Arizona St",
    "Arkansas State": "Arkansas St",
    "Ball State": "Ball St",
    "Boise State": "Boise St",
    "Central Michigan": "C Michigan",
    "Coastal Carolina": "Coastal Car",
    "Colorado State": "Colorado St",
    "East Carolina": "E Carolina",
    "Eastern Michigan": "E Michigan",
    "Florida International": "Florida Intl",
    "Florida State": "Florida St",
    "Fresno State": "Fresno St",
    "Georgia Southern": "Georgia So",
    "Georgia State": "Georgia St",
    "Hawaii": "Hawai'i",
    "Iowa State": "Iowa St",
    "James Madison": "J Madison",
    "Jacksonville State": "Jacksonville St",
    "Kansas State": "Kansas St",
    "Kennesaw State": "Kennesaw St",
    "Kent State": "Kent St",
    "Miami (OH)": "Miami OH",
    "Michigan State": "Michigan St",
    "Middle Tennessee": "Middle Tenn",
    "Ole Miss": "Mississippi",
    "Mississippi State": "Mississippi St",
    "Missouri State": "Missouri St",
    "Northern Illinois": "N Illinois",
    "North Texas": "N Texas",
    "New Mexico State": "New Mexico St",
    "Ohio State": "Ohio St",
    "Oklahoma State": "Oklahoma St",
    "Oregon State": "Oregon St",
    "Penn State": "Penn St",
    "South Alabama": "S Alabama",
    "South Florida": "S Florida",
    "San Diego State": "San Diego St",
    "San Jose State": "San Jose St",
    "San José State": "San Jose St",
    "Southern Mississippi": "Southern Miss",
    "Texas State": "Texas St",
    "Connecticut": "UConn",
    "Massachusetts": "UMass",
    "Utah State": "Utah St",
    "Western Kentucky": "W Kentucky",
    "Western Michigan": "W Michigan",
    "Washington State": "Washington St",
}

def normalize_names(df, columns, name_map):
    for col in columns:
        df[col] = df[col].replace(name_map)
    return df